### ISSUE TITLE
Docker-compose file Version mismatch

### ISSUE THREAD

**Issue by VA2XJM** [mattermost/docker#12]
```
user@test:~/docker/mattermost$ sudo docker-compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d
ERROR: Version mismatch: file ./docker-compose.yml specifies version 2.4 but extension file ./docker-compose.without-nginx.yml uses version 3.0
```

I changed docker-compose.without-nginx.yml version to 2.4 so it can proceed.

**Comment by metanerd** [comment]
Thank you for reporting this @VA2XJM ! I created a PR to change the version: https://github.com/mattermost/docker/pull/14

**Comment by mrckndt** [comment]
Thanks for reporting! It's fixed with https://github.com/mattermost/docker/pull/14.
