### ISSUE TITLE
Is it compatible with the MATTERMOST_IMAGE_TAG equal 8.1?

### ISSUE THREAD

**Issue by iVegas** [mattermost/docker#136]
Is there any upgrade guide for setup with 7.8 image tag?

**Comment by lomax** [comment]
I installed it recently and from the user point of view the answer to your question about MATTERMOST_IMAGE_TAG is yes and no. 

On the 20.11.2023 the dockerhub repo state is following 
 * [8.1](https://hub.docker.com/layers/mattermost/mattermost-team-edition/8.1/images/sha256-a920cfbc0e59d890506e76c7fcb861ea8b84a1c8c07a521c611d89fd9df41a94?context=explore)  image tag seems to be stuck at [8.1.4](https://hub.docker.com/layers/mattermost/mattermost-team-edition/8.1.4/images/sha256-a920cfbc0e59d890506e76c7fcb861ea8b84a1c8c07a521c611d89fd9df41a94?context=explore) 
 *  latest released image is [8.1.6](https://docs.mattermost.com/upgrade/extended-support-release.html), however [release-8.1](https://hub.docker.com/layers/mattermost/mattermost-team-edition/release-8.1/images/sha256-8bbc37b65d37a7e6a5508d90378a2a1621c0114b84c50e53b3a17bcb0f54f504?context=explore)  tag currently points to something [21628_688c31d5](https://hub.docker.com/layers/mattermost/mattermost-team-edition/21628_688c31d5/images/sha256-8bbc37b65d37a7e6a5508d90378a2a1621c0114b84c50e53b3a17bcb0f54f504?context=explore), that reports itself as 8.1.7 and 8.1.5-rc1 simultaneously 
![simultaneously ](https://github.com/mattermost/docker/assets/691748/147cd04e-6fdb-4a4d-b173-327bf4afefde)

So it seems currently to be on the latest released ESR point release you should change MATTERMOST_IMAGE_TAG manually every point release.

**Comment by iVegas** [comment]
Thanks
