### ISSUE TITLE
Failed to ping DB, after cleaning up duplicate indexes

### ISSUE THREAD

**Issue by insomniacslk** [mattermost/docker#148]
Hi,

I've been using the docker container without problems for a long time, but I recently stumbled into an issue: no images could be uploaded. This was caused by postgres errors like `ERROR:  missing chunk number 0 for toast value 53340 in pg_toast_2619`, un turn caused by duplicate indexes. I cleaned up the indexes, but after restarting the application fails with "Failed to ping DB".

I can connect to the database without problems (`psql mattermost mmuser`) and see the database content without problems. I am not sure how to increase the logging and understand what's exactly failing on the application side, but this is not firewalling or other network issues. The setup has not changed since it was last working, just the database content after the index drop and the reindexing of the affected table.

## logs

The relevant application log lines are
```
mattermost_1  | {"timestamp":"2024-04-18 22:46:56.557 Z","level":"info","msg":"Server is initializing...","caller":"platform/service.go:173","go_version":"go1.20.7"}
mattermost_1  | {"timestamp":"2024-04-18 22:46:56.558 Z","level":"info","msg":"Pinging SQL","caller":"sqlstore/store.go:261","database":"master","dataSource":"postgres://%2A%2A%2A%2A:%2A%2A%2A%2A@postgres:5432/mattermost?connect_timeout=10&sslmode=disable"}
mattermost_1  | {"timestamp":"2024-04-18 22:46:56.579 Z","level":"error","msg":"Failed to ping DB","caller":"sqlstore/store.go:269","database":"master","dataSource":"postgres://%2A%2A%2A%2A:%2A%2A%2A%2A@postgres:5432/mattermost?connect_timeout=10&sslmode=disable","retrying in seconds":10,"error":"pq: the database system is shutting down"}
```

The database logs are:
```
postgres_1    | 2024-04-18 22:47:05.379 UTC [1] LOG:  starting PostgreSQL 13.14 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres_1    | 2024-04-18 22:47:05.380 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1    | 2024-04-18 22:47:05.381 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1    | 2024-04-18 22:47:05.384 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2024-04-18 22:47:05.395 UTC [23] LOG:  database system was interrupted; last known up at 2024-04-18 21:56:06 UTC
postgres_1    | 2024-04-18 22:47:05.537 UTC [23] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1    | 2024-04-18 22:47:05.543 UTC [23] LOG:  redo starts at 3/FA9FD500
postgres_1    | 2024-04-18 22:47:05.543 UTC [23] LOG:  invalid record length at 3/FA9FD5F8: wanted 24, got 0
postgres_1    | 2024-04-18 22:47:05.543 UTC [23] LOG:  redo done at 3/FA9FD5B8
postgres_1    | 2024-04-18 22:47:05.577 UTC [1] LOG:  database system is ready to accept connections
```

Thanks in advance for any help you can provide

**Comment by insomniacslk** [comment]
well, I "solved" it by recovering what I could recover and created another instance

**Comment by lil5** [comment]
It's attempting to connect to the database defined by the configs default value

IMO the default value for a database connection should be an empty string, and the go application should exit on seeing an empty string for the sql connection string.

debugging this is not fun otherwise.
