### ISSUE TITLE
Incorrect Client Plugin Volume

### ISSUE THREAD

**Issue by atreides322** [mattermost/docker#16]
It looks like the client plugin is getting bound incorrectly:
https://github.com/mattermost/docker/blob/ac96896538436a65d421d7f14f4e21ee2b688715/docker-compose.yml#L45

Based on the volumes in the Dockerfile for both the official image and the community image, this should be `/mattermost/client/plugins`:
https://github.com/mattermost/mattermost-server/blob/e5386043453bc05264609f1a77fafb66aeea0857/build/Dockerfile#L50
https://github.com/mattermost/mattermost-docker/blob/ed8a619d3981060679afe80087f2e6a6be315b3c/app/Dockerfile#L57

It looks like the community version used `client-plugins/` but mapped it to `client/plugins/`:
https://github.com/mattermost/mattermost-docker/blob/ed8a619d3981060679afe80087f2e6a6be315b3c/docker-compose.yml#L37

I'm no sure if it is preferable to just change the compose file to `${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw`, or if `MATTERMOST_CLIENT_PLUGINS_PATH` should also be expanded out to `./volumes/app/mattermost/client/plugins`, similar to how the DB data is in `env.example`.
https://github.com/mattermost/docker/blob/ac96896538436a65d421d7f14f4e21ee2b688715/env.example#L18

**Comment by mrckndt** [comment]
Thank you for reporting @atreides322. https://github.com/mattermost/docker/pull/17 fixes this and for consistency reasons both the docker-compose.yml and env.example will be changed.
