### ISSUE TITLE
README Typo error

### ISSUE THREAD

**Issue by cobenash** [mattermost/docker#22]
Removing The Docker Containers
Remove the containers

```
sudo docker-compose -f docker-compose.yml -f docker-compose.nginx.ymp down
# OR
sudo docker-compose -f docker-compose.yml -f docker-compose.without-nginx.yml down
```

It should be `sudo docker-compose -f docker-compose.yml -f docker-compose.nginx.yml down`

**Comment by mrckndt** [comment]
Thank you for the PR. Closing this as i merged it.
