### ISSUE TITLE
Upgrade Old mattermost-docker

### ISSUE THREAD

**Issue by PeterPilley** [mattermost/docker#27]
Hi everyone, 

Thanks for an absolutely awesome platform. 

I have a question about the upgrade scripts. is it possible to simply restore an old database dump to a new instance as opposed to upgrading an existing instance?

**Comment by mrckndt** [comment]
@PeterPilley sure you can dump your database(s) with `pg_dump` or `pg_dumpall`, use a newer container and restore from the dump.
