### ISSUE TITLE
Upgrade script fails if mattermost-docker is used with .env

### ISSUE THREAD

**Issue by lu40** [mattermost/docker#31]
While migrating to the new PostgreSQL and Mattermost versions using the [upgrade-from-mattermost-docker.sh](https://github.com/mattermost/docker/blob/main/scripts/upgrade-from-mattermost-docker.sh) script, we encountered a problem with the parsed environment variables. The [docker command to upgrade the db at L179-L186 of the script](https://github.com/mattermost/docker/blob/main/scripts/upgrade-from-mattermost-docker.sh#L179-L186) fails with the following message:

```
initdb: option requires an argument -- 'U'
```

This is only an assumption as we haven't been reproducing this error, but we guess that the problem lies in having used variables from .env with mattermost-docker like this:

```yml
environment:
  - POSTGRES_USER=${POSTGRES_USER}
  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  - POSTGRES_DB=${POSTGRES_DB}
```
So when exporting the variables in the shell the docker command worked as expected.

Thanks a lot for the great work you put into restructuring the docker setup for mattermost.

**Comment by mrckndt** [comment]
@lu40 thank you for reporting. Because there are efforts in improving the upgrade i'm closing this in favor of https://github.com/mattermost/docker/pull/25.
