### ISSUE TITLE
Missing certificate signed by unknown authority

### ISSUE THREAD

**Issue by craph** [mattermost/docker#34]
Hello @jasonblais ,

Sorry for the time without no news about my tests.
After reviewing the code in the `docker-compose.yml` I think there is something missing. 
The 13 may 2020 I fix an issue about self-signed certificate : https://github.com/mattermost/mattermost-docker/pull/474 for this issue : https://github.com/mattermost/mattermost-server/issues/13059

I think, this is missing in the new repository. 
Can I reopen a PR for this ?

Thank you very much.

_Originally posted by @craph in https://github.com/mattermost/mattermost-docker/pull/529#issuecomment-912340798_

**Comment by jasonblais** [comment]
@craph Thank you! That would be great if you're open to sending a PR for it. Our team can then review the changes.

**Comment by craph** [comment]
@jasonblais @mrckndt I have created the PR 😃 Feel free to tell me if something is wrong.
Thank you.

**Comment by jasonblais** [comment]
Thank you @craph!

**Comment by craph** [comment]
> Thank you @craph!

You are welcome
