### ISSUE TITLE
WAL-E backups to AWS S3

### ISSUE THREAD

**Issue by cobenash** [mattermost/docker#37]
The original git repo `mattermost/mattermost-docker` has the WAL-E supports to deploy to AWS S3.

> AWS
> If deploying to AWS, you could also set following variables to enable Wal-E backup to S3 :
> AWS_ACCESS_KEY_ID: AWS access key
> AWS_SECRET_ACCESS_KEY: AWS secret
> WALE_S3_PREFIX: AWS s3 bucket name
> AWS_REGION: AWS region
> All four environment variables are required. It will enable completed WAL segments sent to archive storage (S3). The base backup and clean up can be done through the following command:

It will be nice if we could have this kind of backup function in the current repo.

**Comment by mrckndt** [comment]
Hey, while i think this can be really useful the intention of this deployment is not to use custom entrypoints but the official images such as Nginx, Postgres and the Mattermost one. I'd suggest to use a separate container image with access to the Postgres volume to use WAL-E. For now i'll close this issue but i'm open to merge a docker-compose file with such an container setup as contrib.
