### ISSUE TITLE
Session is expiring on each site refresh

### ISSUE THREAD

**Issue by Szymon-Rysztof** [mattermost/docker#43]
Hi, i have issue with sessions in my mattermost instance. 
First of all, i'm coming from mattermost-docker, i've used upgrade script to move to the new repo. 

The problem is: 
On each page refresh or desktop app re-run (Right-click > exit from tray and then run), logged user is losing his session. 
I'm running Haproxy reverse-proxy which is also ssl terminator. 

docker version:  
`Docker version 20.10.6, build 370c289`

docker-compose version:
`docker-compose version 1.28.5, build c4eb3a1f` 

Host: 
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
```

Mattermost server: 
```
Team edition
Mattermost Version: 5.39.0
Database Schema Version: 5.39.0
Database: postgres
```

Of course i will provide logs, but i would need to know, which one do you need.

**Comment by mrckndt** [comment]
@Szymon-Rysztof this sounds like a configuration problem in your HAproxy to me. Is you proxy configured like the Nginx docs page suggests (https://docs.mattermost.com/install/config-proxy-nginx.html)? Are `X-Real-IP` and `X-Forwarded-For` set accordingly?
> Of course i will provide logs, but i would need to know, which one do you need.
The log in question is the *mattermost.log* probably found in your install directory und *logs*.

**Comment by mrckndt** [comment]
In case this is still a problem please reopen and provide the logs.
