### ISSUE TITLE
Differences between tags "6.0" and "release-6.0"?

### ISSUE THREAD

**Issue by R8s6** [mattermost/docker#66]
Hi,

In the [docker hub release page](https://hub.docker.com/r/mattermost/mattermost-team-edition/tags), what are the differences between tags `6.0` and `release-6.0`?

Also, is the `master` tag good for production, or is it mainly for testing?

Thanks!

**Comment by cpanato** [comment]
@R8s6 `release-6.0` is the latest code from the release branch, should not use for production and this tag will be removed from the repository soon, we are doing some cleanups on that.

the `master` tag is the latest code from the main branch, should not use in production as well, but if you want to live in the edge you can use that :)

**Comment by R8s6** [comment]
@cpanato Thanks for hte explanation!
