### ISSUE TITLE
MM6.0.2: unable to generate webapp bundle: ¸Jitsi: unable to copy webapp bundle directory: jitsi: mkdir client/plugins/jitsi: permission denied

### ISSUE THREAD

**Issue by VA2XJM** [mattermost/docker#71]
I get lots of error when trying to install plugins: unable to generate webapp bundle: jitsi: unable to copy webapp bundle directory: jitsi: mkdir client/plugins/jitsi: permission denied

Going into the container shell, it seems a folder is not owned properly. It is off course applicable to all plugins.

![image](https://user-images.githubusercontent.com/13443249/141047401-4d6487f2-31da-4609-817f-463bc99df2ee.png)

**Comment by mrckndt** [comment]
@VA2XJM are you running the Mattermost container in *read_only* mode? - if so you need to set this to false otherwise it's not writable. Or is your host using SELinux? - Then you probably want to change the occurrences of **:rw** in the volume definitions to **:Z**.

**Comment by VA2XJM** [comment]
@mrckndt Sorry, I totally forgot to update the ticket when I fixed it.

This situation arised after the update from previous version (6.0.1). From inside the container, I add to chown the plugins folder for MM to be back on track with plugins. No apparent reason why and no clues in the logs about that... read_only mode not used.

Anyway once the folder as been CHOWN to user `mattermost` everything came back to normal.

It can be closed if no one else claim the same problem.
