### ISSUE TITLE
postgres_mattermost container - FATAL:  database "mattermost" does not exist

### ISSUE THREAD

**Issue by rubiusus** [mattermost/docker#72]
Hi,
in a from scratch installation, I get this error in postgres_mattermost container's log:
`FATAL:  database "mattermost" does not exist`

**Comment by craph** [comment]
Hello @rubiusus ,

Please can you give us more details about the installation process you followed ?
Thx

**Comment by rubiusus** [comment]
Hello @craph,
in the meanwhile I migrated directly from mattermost-docker and worked fine.

Thank you for your reply.

**Comment by dominikfehr** [comment]
> Hello @rubiusus ,
> 
> Please can you give us more details about the installation process you followed ? Thx

same error with installation as explained via README

team-version used with tag 6.3
