### ISSUE TITLE
Cannot run bash file in script folder

### ISSUE THREAD

**Issue by KyoRion** [mattermost/docker#73]
I got this error when trying Encrypt with file sh
![image](https://user-images.githubusercontent.com/26852023/142820641-de547027-8807-4d66-b12a-ac5f99a8c45f.png)

**Comment by craph** [comment]
Hello @KyoRion ,

Did you have a look to this part of the README.md : https://github.com/mattermost/docker#53-lets-encrypt ?

**Comment by mrckndt** [comment]
@KyoRion Let me guess: you're using somehow Windows?
