### ISSUE TITLE
docker compose install environments not found

### ISSUE THREAD

**Issue by manox-myth** [mattermost/docker#82]
Hello. when I run the script, it does not find the values of my .env file:

~/docker$ docker-compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d
WARNING: The POSTGRES_IMAGE_TAG variable is not set. Defaulting to a blank string.
WARNING: The RESTART_POLICY variable is not set. Defaulting to a blank string.
WARNING: The POSTGRES_DATA_PATH variable is not set. Defaulting to a blank string.
WARNING: The MATTERMOST_IMAGE variable is not set. Defaulting to a blank string.
WARNING: The MATTERMOST_IMAGE_TAG variable is not set. Defaulting to a blank string.
WARNING: The MATTERMOST_CONTAINER_READONLY variable is not set. Defaulting to a blank string.
ERROR: Error while attempting to convert service.mattermost.read_only to appropriate type: "" is not a valid boolean value

Running Ubuntu server 20.04, docker and docker-compose are latest versions.

**Comment by krishnarastogi** [comment]
Firnt run copy env file 
$cp env.example .env
$docker-compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d

**Comment by craph** [comment]
@manox-myth ,

Did you made a copy of the env.example file first ?

1. `cp env.example .env`
2. customize the `.env` file as needed for you
3. Run `docker-compose -f docker-compose.yml -f docker-compose.nginx.yml up -d` if you need nginx 
4. Run `docker-compose -f docker-compose.yml -f docker-compose.without-nginx.yml up -d` if you don't need nginx

**Comment by mrckndt** [comment]
@manox-myth The above tips are correct and you need a recent Docker compose version. Older versions can't interpolate variables inside variables.
